version: '3.1'

services:

  golang_todo_rethinkdb:
    image: rethinkdb:2.3.5
    container_name: golang_todo_rethinkdb
    ports:
      - "8080:8080"
      - "28015:28015"
    volumes:
      - golang_todo_rethink_data:/data
    networks:
      - golang_todo_network

  golang_todo_backend:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile-golang-glide
    container_name: golang_todo_backend
    working_dir: /go/src/github.com/tokillamockingbird/golang-todo
    command: /bin/sh -c "cd backend &&
              go get -u github.com/pressly/chi &&
              go get gopkg.in/gorethink/gorethink.v3 &&
              go get github.com/spf13/viper &&
              go get github.com/codegangsta/gin &&
              go build && ./backend"
    ports:
      - "8000:8000"
    volumes:
      - .:/go/src/github.com/tokillamockingbird/golang-todo/
      - golang_todo_backend_data:/go/src
    networks:
      - golang_todo_network
    environment:
      - GOPATH=/go

volumes:
  golang_todo_rethink_data:
    driver: local
  golang_todo_backend_data:
    driver: local

networks:
  golang_todo_network:
    driver: bridge
