FROM golang:1.8.0

MAINTAINER tokillamockingbird <tokillamockingbird1989@gmail.com>

RUN go get github.com/Masterminds/glide

WORKDIR $GOPATH/src/github.com/Masterminds/glide

RUN make build

RUN glide -v
